#!/bin/sh

make clean
CFLAGS="-g -Og --coverage" LDFLAGS="--coverage" make

fail()
{
	echo $@
	exit 1
}

do_ks()
{
	if [ "$VG" != "" ]; then
		valgrind \
			--error-exitcode=2 \
			--leak-check=full \
			--show-leak-kinds=all \
			--errors-for-leak-kinds=all \
			--quiet \
			./ks -d ks.db "$@" || exit 2
	else
		./ks -d ks.db "$@" || exit 2
	fi
}

for t in test/*.sh; do
	. $t
	rm -f ks.db
done

gcov --relative-only ks.c cli.c
